INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros","16.77","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum","51.36","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus","45.52","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem","37.02","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit","5.67","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis","7.46","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","Sed molestie. Sed id risus quis","84.16","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam","36.30","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi","15.66","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis","0.51","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","Lorem ipsum dolor sit","56.54","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum.","36.04","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie","22.70","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras","5.16","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus","76.07","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","ornare egestas ligula.","14.70","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue","13.00","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin","70.93","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut","33.84","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","Ut tincidunt","98.45","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna.","10.77","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","In ornare sagittis felis. Donec","30.06","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis.","98.31","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","euismod mauris eu elit. Nulla facilisi. Sed","33.50","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse","15.54","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla","73.38","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","metus. In lorem.","89.13","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis","49.41","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","nec tellus. Nunc","13.43","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis","68.02","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem.","73.01","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","gravida nunc sed pede.","21.19","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","Morbi quis urna. Nunc quis arcu vel quam","56.12","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse","22.19","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies","31.51","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur","4.04","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","lorem lorem, luctus ut,","15.49","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","mauris,","64.31","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","fermentum arcu. Vestibulum ante ipsum primis in faucibus orci","90.05","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames","100.00","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum","14.36","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","lorem. Donec elementum, lorem","14.80","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","arcu. Aliquam ultrices iaculis odio. Nam interdum","41.55","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor.","54.28","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","aliquet odio. Etiam","14.04","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis","50.08","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient","96.81","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam","89.91","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam","44.42","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","Cras eget nisi dictum augue malesuada malesuada. Integer id","1.36","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","morbi tristique senectus et netus et malesuada fames ac","90.10","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut,","91.24","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue","80.17","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","gravida. Aliquam tincidunt, nunc","21.75","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","elit. Aliquam auctor, velit eget laoreet posuere, enim","73.84","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","erat vel","6.87","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","ac risus.","11.50","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","vel lectus. Cum sociis natoque penatibus et magnis dis","49.72","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui,","69.97","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","tellus. Phasellus elit pede, malesuada vel, venenatis","77.14","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur","35.29","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas","5.89","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam","34.85","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse","52.39","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum","99.24","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere","50.67","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","lorem tristique aliquet. Phasellus fermentum convallis","27.57","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","a, scelerisque sed, sapien. Nunc pulvinar","92.24","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna","42.71","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim.","82.73","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris","31.00","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor","3.19","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis","46.67","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","leo elementum sem, vitae","88.83","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae","68.02","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla,","21.18","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","magna. Sed","97.87","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum","24.27","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada","24.03","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","Donec tempus, lorem fringilla ornare placerat,","80.39","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque","4.53","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus","74.81","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis","32.23","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis","37.84","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","libero. Proin sed","0.29","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","sapien. Aenean massa. Integer","36.96","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue","96.42","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque","21.76","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","ornare","2.72","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","egestas nunc sed libero. Proin sed turpis nec mauris","54.45","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc","80.56","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","aliquam eros turpis non enim. Mauris quis","85.86","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam.","21.28","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu.","58.49","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut","2.30","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem","neque.","45.25","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin","87.94","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam","72.03","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum","Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non","41.21","1","1");
INSERT INTO `tasks` (`title`,`description`,`budget`,`users_id`,`budget_type`) VALUES ("Lorem ipsum dolor","Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque","72.32","1","1");


INSERT INTO `tasks_tags` (`tag`) VALUES ("pede,");
INSERT INTO `tasks_tags` (`tag`) VALUES ("metus.");
INSERT INTO `tasks_tags` (`tag`) VALUES ("diam.");
INSERT INTO `tasks_tags` (`tag`) VALUES ("aptent");
INSERT INTO `tasks_tags` (`tag`) VALUES ("lobortis,");
INSERT INTO `tasks_tags` (`tag`) VALUES ("enim.");
INSERT INTO `tasks_tags` (`tag`) VALUES ("Curabitur");
INSERT INTO `tasks_tags` (`tag`) VALUES ("nisi");
INSERT INTO `tasks_tags` (`tag`) VALUES ("arcu.");
INSERT INTO `tasks_tags` (`tag`) VALUES ("tellus.");
INSERT INTO `tasks_tags` (`tag`) VALUES ("Aliquam");

INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (48,1);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (97,1);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (95,9);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (34,6);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (47,6);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (78,5);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (11,5);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (73,3);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (90,5);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (72,3);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (67,2);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (99,3);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (13,8);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (64,1);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (100,9);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (87,6);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (79,10);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (54,8);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (58,10);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (25,1);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (39,1);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (50,6);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (44,3);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (69,4);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (61,5);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (54,3);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (51,6);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (48,7);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (20,2);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (70,3);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (88,7);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (67,8);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (41,3);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (39,11);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (7,7);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (3,5);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (65,6);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (94,1);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (75,7);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (41,4);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (3,11);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (61,6);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (48,1);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (17,8);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (21,10);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (87,1);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (43,6);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (75,10);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (74,2);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (83,9);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (77,10);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (26,5);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (38,3);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (49,2);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (82,10);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (47,10);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (84,1);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (37,4);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (17,6);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (98,5);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (40,10);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (45,10);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (37,3);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (66,2);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (33,6);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (90,1);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (33,2);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (50,8);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (34,11);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (83,2);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (88,4);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (99,8);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (37,4);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (2,6);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (89,11);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (91,4);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (84,4);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (10,3);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (55,9);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (31,10);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (24,3);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (95,7);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (35,5);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (28,8);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (42,2);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (83,4);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (39,9);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (100,9);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (17,1);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (30,1);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (2,3);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (34,10);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (55,5);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (6,1);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (19,4);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (95,5);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (56,10);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (100,10);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (33,3);
INSERT INTO `tasks_has_tags` (`tasks_id`,`tasks_tags_id`) VALUES (58,9);

